if [[ $- == *i* ]] ; then
  export IS_INTERACTIVE=true
else
  export IS_INTERACTIVE=false
fi

if [[ -z $SSH_CONNECTION ]]; then
  export IS_REMOTE=false
else
  export IS_REMOTE=true
fi



# Colors ----------------------------------------------------------
export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1 

eval `dircolors ~/.dir_colors` # Set solarized dir colors

alias ls='ls --color=auto'

# Setup some colors to use later in interactive shell or scripts
export COLOR_NC='\033[0m' # No Color
export COLOR_WHITE='\033[1;37m'
export COLOR_BLACK='\033[0;30m'
export COLOR_BLUE='\033[0;34m'
export COLOR_LIGHT_BLUE='\033[1;34m'
export COLOR_GREEN='\033[0;32m'
export COLOR_LIGHT_GREEN='\033[1;32m'
export COLOR_CYAN='\033[0;36m'
export COLOR_LIGHT_CYAN='\033[1;36m'
export COLOR_RED='\033[0;31m'
export COLOR_LIGHT_RED='\033[1;31m'
export COLOR_PURPLE='\033[0;35m'
export COLOR_LIGHT_PURPLE='\033[1;35m'
export COLOR_BROWN='\033[0;33m'
export COLOR_YELLOW='\033[1;33m'
export COLOR_GRAY='\033[1;30m'
export COLOR_LIGHT_GRAY='\033[0;37m'
alias colorslist="set | egrep 'COLOR_\w*'"  # lists all the colors



# History ----------------------------------------------------------
export HISTCONTROL=ignoredups
#export HISTCONTROL=erasedups
export HISTFILESIZE=3000
export HISTIGNORE="ls:cd:[bf]g:exit:..:...:ll:lla"
alias h=history
hf(){ 
  grep "$@" ~/.bash_history
}



if [ $IS_INTERACTIVE = 'true' ] ; then # Interactive shell only

  # Input stuff -------------------------------------------------------
  bind "set completion-ignore-case on" # note: bind used instead of sticking these in .inputrc
  bind "set show-all-if-ambiguous On" # show list automatically, without double tab
  bind "set bell-style none" # no bell

  # Use vi command mode
  #bind "set editing-mode vi"
  #set -o vi
  #bind -m vi-command -r 'v'

  shopt -s checkwinsize # After each command, checks the windows size and changes lines and columns



  # Completion -------------------------------------------------------

  # Turn on advanced bash completion if the file exists
  # Get it here: http://www.caliban.org/bash/index.shtml#completion
  if [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
  fi
  if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
  fi

  # Prompts ----------------------------------------------------------

  # disable virtualenv prompt modification. Its not compatible with this stuff
  # and it doesn't work with PROMPT_COMMAND anyway
  VIRTUAL_ENV_DISABLE_PROMPT=1

  prompt_func() {
      previous_return_value=$?;

      # Set the color of the path depending on if we're local or ssh'd in
      if [ $IS_REMOTE = 'true' ] ; then
        path="\[${COLOR_PURPLE}\]\w\[${COLOR_NC}\]"
      else
        path="\[${COLOR_GREEN}\]\w\[${COLOR_NC}\]"
      fi

      # git branch and info. Display in red if branch is "dirty"
      if [[ $(git status --porcelain 2> /dev/null | tail -n1) != "" ]] ; then
          git_branch="\[${COLOR_RED}\]$(__git_ps1)\[${COLOR_NC}\]"
        else
          git_branch="\[${COLOR_WHITE}\]$(__git_ps1)\[${COLOR_NC}\]"
        fi

      # virtualenv info
      if [ -z "${VIRTUAL_ENV-}" ] ; then
           venv=''
      else
           venv="[venv: \[${COLOR_BLUE}\]${VIRTUAL_ENV##*/}\[${COLOR_NC}\]] "
      fi

      # if our last command ended in error, display red prompt
      if test $previous_return_value -eq 0
      then
          prompt_char=">"
      else
          prompt_char="\[${COLOR_RED}\]>\[${COLOR_NC}\]"
      fi

      # put it all together
      PS1="${venv}${path}${git_branch}${prompt_char} "
  }

  PROMPT_COMMAND=prompt_func

  export PS2='> '    # Secondary prompt
  export PS3='#? '   # Prompt 3
  export PS4='+'     # Prompt 4

  function xtitle {  # change the title of your xterm* window
    unset PROMPT_COMMAND
    echo -ne "\033]0;$1\007" 
  }

fi



# Navigation -------------------------------------------------------
alias ..='cd ..'
alias ...='cd .. ; cd ..'
cl() { cd $1; ls -la; }

if type -P zoxide &>/dev/null ; then
  eval "$(zoxide init bash)"
fi



# Editors ----------------------------------------------------------
export EDITOR='vim'  #Command line
export GIT_EDITOR='vim'
alias v=vim



# Security ---------------------------------------------------------

# Folder shared by a group
# chmod g+s directory 
#find /foo -type f -print | xargs chmod g+rw,o-rwx,u+rw
#find /foo -type d -print | xargs chmod g+rwxs,o-rwx,u+rwx

# this might work just the same (not tested)
# chmod -R g+rwXs,o-rwx,u+rwX /foo



# Sluething----------------------------------------------------
findportuser() {
    lsof -i :"$1"
}

findhosts(){
  nmap -sP -n -oG - "$1"/24 | grep "Up" | awk '{print $2}' -
  echo "To scan those do: nmap $1-254"
  echo "To scan and OS detect those do: sudo nmap -O $1-254"
  echo "To intensly scan one do: sudo nmap -sV -vv -PN $1"
}

find_large_files(){
  fd -t f -S +50m
}


# Other aliases ----------------------------------------------------
alias ll='ls -hl'
alias la='ls -a'
alias lla='ls -lah'
alias c='clear'

# Search
if type -P rg &>/dev/null ; then
  g(){
    rg "$*" --smart-case
  }
  gw(){
    rg "$*" --smart-case --word-regexp
  }
  gnolog(){
    rg "$*" --smart-case --glob '!log/'
  }
  f(){
    rg --files | rg -i "$*"
  }
else
  g(){
    grep -Rin $1 *
  }
  f(){
    find . -iname "$1"
  }
fi


# Misc
alias reloadbash='source ~/cl/etc/bash_profile'

alias ducks='dust -d 1' # Lists folders and files sizes in the current folder
alias bigfilesandfolders='dust'
alias m='more'
alias top='top -o %CPU'

alias df='df -h' # Show disk usage

# Shows most used commands, cool script I got this from: http://lifehacker.com/software/how-to/turbocharge-your-terminal-274317.php
alias profileme="history | awk '{print \$2}' | awk 'BEGIN{FS=\"|\"}{print \$1}' | sort | uniq -c | sort -n | tail -n 20 | sort -nr"

alias cp_folder="cp -Rpv" #copies folder and all sub files and folders, preserving security and dates

alias mirror_website="wget -m -x -p --convert-links --no-host-directories --no-cache -erobots=off"

killhard() {
    kill -9 "$1"
}



if [ -f ~/.bashrc_local ]; then
  source ~/.bashrc_local
fi
