#!/usr/bin/env bash

if [ -z "$PS1" ]; then
  echo -e "${COLOR_RED}You should source this, not run it, for example: source ./link${COLOR_NC}"
else

  link (){
    if [ -e $1 ]; then
      if [ -e $2 ]; then
        rm $2
      fi

      ln -s $1 $2
    fi
  }

  # bash
  link ~/cl/etc/profile ~/.profile
  link ~/cl/etc/bash_profile ~/.bash_profile
  link ~/cl/etc/bashrc ~/.bashrc
  link ~/cl/etc/dircolors.ansi-dark ~/.dir_colors

  # vim
  link ~/cl/etc/vim/vimrc ~/.vimrc
  link ~/cl/etc/vim/gvimrc ~/.gvimrc
  link ~/cl/etc/vim ~/.vim

  # git
  link ~/cl/etc/gitconfig ~/.gitconfig
  link ~/cl/etc/gitignore ~/.gitignore

  source ~/.bash_profile

fi
