" -----------------------------------------------------------------------------  
" |                            VIM Settings                                   |
" |                              GUI stuff                                    |
" -----------------------------------------------------------------------------  


" OS Specific *****************************************************************
if has("gui_gtk2")
  set guifont=DejaVu\ Sans\ Mono\ 10
  set guioptions-=T  " remove toolbar
endif

" General *********************************************************************
set anti " Antialias font

"set transparency=0

" Default size of window
set columns=179 
set lines=50

" Tab headings 
set gtl=%t gtt=%F
